# Generated by Django 3.0.8 on 2020-07-28 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel', models.CharField(choices=[('brahmaputra', 'BRAHMAPUTRA'), ('dihing', 'DIHING'), ('lohit', 'LOHIT'), ('manas', 'MANAS'), ('umiam', 'UMIAM'), ('barak', 'BARAK'), ('kameng', 'KAMENG'), ('kapili', 'KAPILI'), ('siang', 'SIANG'), ('dibang', 'DIBANG'), ('disang', 'DISANG'), ('dhansiri', 'DHANSIRI'), ('subhansiri', 'SUBHANSIRI'), ('msh', 'MSH')], default='brahmaputra', max_length=11)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], default='male', max_length=6)),
                ('dp', models.ImageField(blank='True', default='default-pic.jpg', upload_to='user_dp')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
