# Generated by Django 3.0.8 on 2020-07-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createbooking',
            name='peopletogether',
            field=models.IntegerField(default=1),
        ),
    ]
