# Generated by Django 3.0.8 on 2020-07-29 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='details',
            new_name='feedback',
        ),
    ]
