# Generated by Django 3.0.8 on 2020-07-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createbooking',
            name='members_total',
            field=models.IntegerField(default=1),
        ),
    ]
