# Generated by Django 3.0.8 on 2020-07-30 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0002_createbooking_members_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createbooking',
            old_name='members_total',
            new_name='max',
        ),
        migrations.AlterField(
            model_name='createbooking',
            name='peopletogether',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.createbooking')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
