# Generated by Django 3.0.8 on 2020-07-30 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20200730_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='bookings',
            new_name='booking',
        ),
    ]
