# Generated by Django 3.0.8 on 2020-08-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_auto_20200730_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='createbooking',
            name='gender',
            field=models.CharField(choices=[('all', 'all'), ('girls only', 'girls only'), ('boys only', 'boys only')], default='both', max_length=15),
        ),
    ]
