# Generated by Django 3.0.8 on 2020-08-01 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_createbooking_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createbooking',
            old_name='gender',
            new_name='gender_choice',
        ),
    ]
