# Generated by Django 3.0.8 on 2020-08-01 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_auto_20200801_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createbooking',
            name='gender_choice',
        ),
    ]
