# Generated by Django 3.0.8 on 2020-08-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_remove_createbooking_gender_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='createbooking',
            name='gender_choice',
            field=models.CharField(choices=[('all', 'all'), ('girls only', 'girls only'), ('boys only', 'boys only')], default='both', max_length=15),
        ),
    ]
